# The URL the site will be built for
base_url = "https://caohc.me"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "linkita"

generate_feeds = true

[[taxonomies]]
name = "categories"
feed = true
paginate_by = 4

[[taxonomies]]
name = "tags"
feed = true
paginate_by = 4

[[taxonomies]]
name = "authors"
feed = true
paginate_by = 4

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
comment = true
disable_default_favicon = true

# Header menu configuration
menu = [
    { name = "About", url = "/about/" },
    { name = "Projects", url = "/projects/" },
    { name = "Notes", url = "/notes/" },
]

[extra.style]
bg_color = "#eff1f5"
bg_dark_color = "#181825"

# header_color = "#04a5e5"
# header_dark_color = "#89dceb"

header_blur = true

[extra.profiles.caohc]
name = "Steven Cao"
avatar_url = "https://csclub.uwaterloo.ca/~s3cao/blog/icons/avatar.jpg"
avatar_invert = false
bio = "Computer Science + AI Specialization @ University of Waterloo"
social = [
    { name = "github", url = "https://github.com/UltimateBoomer" },
    { name = "email", url = "mailto:s3cao@uwaterloo.ca" },
    { name = "rss", url = "$BASE_URL/atom.xml" },
]

[extra.footer]
copyright = "&copy; $YEAR Haichuan Cao | [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) | Self-hosted on Proxmox VE"

[extra.giscus]
repo = "UltimateBoomer/zola-blog"
repo_id = "R_kgDOPVKPwg"
category = "Announcements"
category_id = "DIC_kwDOPVKPws4CuMpI"
mapping = "pathname"
strict = 1
reactions_enabled = 1
emit_metadata = 0
input_position = "top"
theme = "preferred_color_scheme"
lang = "en"
loading = "lazy"
